<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class ScoreTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('scores')->insert([
            // 10000 Lignes
            // Matricule entre 12534501 et 12534650
            // Score entre 5 et 18
            //student_id 1 a 150
            // matter_id 1 a 11
            // teacher_id 1 a 5
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
            [
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],[
                'student_matricule' => '12534501',
                'score' => 15,
                'student_id' => 1,
                'matter_id' => 1,
                'teacher_id' => 2,
                // 'level_id' => 1,
            ],
        ]);
    }
}
